### PR TITLE
Code Cleanup

### PR DESCRIPTION
**Pull request by darxriggs**
# Description

These are proposed commits to perform different aspects of cleaning up the code.
It's easier to review the commits individually than final diff.
Individual commits can be removed from the pull request if they are not meeting your needs.

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate. (not appropriate)
- [x] Change is code complete and matches issue description.
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests.
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below. (not appropriate)

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description.
- [ ] Reviewed the code.
- [ ] Verified that the appropriate tests have been written or valid explanation given.
- [ ] If applicable, test installing this plugin on the Jenkins instance.

### CODE REVIEW

**Comment by darxriggs** [comment]
Hi @nrayapati, as some time already passed since this pull-request was created, I just wanted to check if it can be merged?

**Comment by nrayapati** [comment]
Thanks for the pull request @darxriggs 

Leave the Lombok dependency on please, it was added intentionally to support the future enhancements. 

And also can you apply [google style](https://google.github.io/styleguide/javaguide.html) formatting. 

Except that everything else looks good to me. Thanks again.

**Comment by darxriggs** [comment]
Using https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml formatting has no impact on current formatting, except 100 chars line length. Therefore I leave the formatting as is.

**Comment by nrayapati** [comment]
Thank you @darxriggs, merging in,  I will take care of formatting in next commit.

**Pull request merged**
