### PR TITLE
remote.proxy.proxy & proxy.type to ProxyType

### PR DESCRIPTION
**Pull request by iameinstein**
# Description

See [JENKINS-53556](https://issues.jenkins-ci.org/browse/JENKINS-53556).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description.
- [x] Appropriate unit or acceptance tests or explanation to why this change has no tests.
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description.
- [ ] Reviewed the code.
- [ ] Verified that the appropriate tests have been written or valid explanation given.
- [ ] If applicable, test installing this plugin on the Jenkins instance.

### CODE REVIEW

**Comment by nrayapati** [comment]
@iameinstein  Thanks for the pull request, I have created a JIRA for this and update the description.

**Comment by nrayapati** [comment]
Nice catch!, we are yet to start using the proxy. 

Changes looks good to me, can you attach the results of test job if any using these changes. Thanks again.

**Comment by iameinstein** [comment]
I deploy the change to our jenkins, seems works fine, sorry can't provide the job output because have sensitive info.

**Comment by nrayapati** [comment]
Thank you @iameinstein thats good, I am okay as soon as it is working. 

Thank you @ghenkes for a quick review.

**Comment by nrayapati** [comment]
This is now released with 1.1.1, it should show up in the update center soon.

**Pull request merged**
